# infra/envs/netcup/global-values.yaml
# Valores globales para el entorno Netcup (producci贸n)

# Configuraci贸n global del entorno
environment:
  name: netcup
  type: production

domain: albertperez.dev
tls: wildcard-netcup-tls

# Configuraci贸n de red
network:
  domain: "albertperez.dev"
  internal: false

# Configuraci贸n de recursos
resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"


certmanager:
  env: prod
  email: admin@albertperez.dev

server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
